server:
  port: 8099
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.88:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
